// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqnvwUr127di1jL-lv_XlA6kaLveZUc54',
    appId: '1:1043589239361:web:aea60e9abc66067f15acc0',
    messagingSenderId: '1043589239361',
    projectId: 'zeroui-catalog',
    authDomain: 'zeroui-catalog.firebaseapp.com',
    storageBucket: 'zeroui-catalog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwpuL-CHBi_VZoLmFhatwTH0Vd7EsYgg',
    appId: '1:1043589239361:android:b5d8c01e56b7ac0b15acc0',
    messagingSenderId: '1043589239361',
    projectId: 'zeroui-catalog',
    storageBucket: 'zeroui-catalog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1aXzn5oqQG4wMDnjBredCk-cJOXBWOzw',
    appId: '1:1043589239361:ios:e4eb0bf8cd14cb0815acc0',
    messagingSenderId: '1043589239361',
    projectId: 'zeroui-catalog',
    storageBucket: 'zeroui-catalog.appspot.com',
    iosClientId: '1043589239361-fsalrjmo0mv6ac4slpuld2bhpphcufrp.apps.googleusercontent.com',
    iosBundleId: 'company.onezero.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1aXzn5oqQG4wMDnjBredCk-cJOXBWOzw',
    appId: '1:1043589239361:ios:2d90abaca377153015acc0',
    messagingSenderId: '1043589239361',
    projectId: 'zeroui-catalog',
    storageBucket: 'zeroui-catalog.appspot.com',
    iosClientId: '1043589239361-8liovhopanlbcvee410go48tvjktmjm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.onezeroUiCatalog',
  );
}
