targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          namespaces: true
          output_directory: lib/i18n
          output_file_name: translations.dart
          input_directory: lib/i18n
          input_file_pattern: .i18n.yaml
          flat_map: false
          locale_handling: false
          translation_class_visibility: public
