name: zero_flutter
description: A new Flutter package project.

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Routing
  go_router: ^6.2.0

  # Riverpod + Hooks (state)
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.0

  # Utils
  url_launcher: ^6.1.10

  # Localization
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  intl: ^0.17.0

  # Authentication
  crypto: ^3.0.2
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^4.3.0

  # User Interface
  flutter_svg: ^2.0.2
  smooth_corner: ^1.1.0

  # Images
  camera: ^0.10.3+2
  image_picker: ^0.8.6+3
  extended_image: ^7.0.2
  image: ^4.0.15

  # Firebase
  cloud_firestore_odm: ^1.0.0-dev.46
  json_annotation: ^4.8.0
  firebase_core: ^2.3.0
  firebase_auth: 4.1.5
  firebase_auth_web: 5.1.3
  cloud_functions: ^4.0.11
  cloud_firestore: ^4.4.3
  firebase_remote_config: ^3.0.13

dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  onezero_flutter_lints:
    git:
      url: https://github.com/onezerocompany/coding.git
      path: packages/onezero_flutter_lints
  build_runner: ^2.3.3
  slang_build_runner: ^3.13.0
  riverpod_generator: ^2.0.0
  custom_lint: ^0.2.12
  riverpod_lint: ^1.1.2

flutter:
  uses-material-design: false
  fonts:
    - family: MaterialSymbolsRounded
      fonts:
        - asset: assets/fonts/material-symbols-rounded.ttf
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/flags/
